version: '3.8'

services:
  fastapi:
    image: python:3.10-slim
    container_name: fastapi_app
    command: poetry run uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app_network

  celery_worker:
    image: python:3.10-slim
    container_name: celery_worker
    command: poetry run celery -A src.worker.celery_app worker --loglevel=debug
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
